### ISSUE TITLE
feat: add checksum

### ISSUE THREAD

**Issue by Dev-JoseRonaldo** [Dev-JoseRonaldo/real-time-udp-chat#22]
- [x] Deve implementar o “checksum” para detecção de erros (Pode usar bibliotecas para auxiliar significativamente)
- [x] Caso não haja erros, deve retornar um pacote de confirmação ao remetente conhecido como “ACK”
- [x] O remetente aguarda a confirmação após enviar o pacote através do ACK, caso não receba um ACK dentro do tempo de **timeout**, a mensagem **deve ser reenviada quantas vezes for necessário** até que a confirmação seja recebida pelo remetente

**Comment by luiz-linkezio** [comment]
Realizei a implementação do checksum apenas nas mensagens normais, não nas mensagens de SIGNUP e QUIT (não sei se é necessário), o motivo foi porque o código está muito despadronizado, então certas implementações ficam muito difíceis e desorganizadas, seria melhor refatorar o código na minha opinião.

Na implementação do checksum de cliente para servidor, ficou bem organizado, porém, na implementação do checksum de servidor para cliente, o pacote não tem header(cabeçalho), não consegui implementar o checksum de maneira convencional, tive que fazer uma "gambiarra" e ficou bem caótico, tive que colocar o checksum dentro da string da mensagem e coletar posteriormente no lado do cliente, horrível. 

Enfim, acho que o código está bastante despadronizado e deveria ser refatorado uma boa parte dele, acho que deveríamos padronizar a forma que formamos e enviamos os pacotes (independente do tipo de mensagem).
